---
apiVersion: v1
kind: Namespace
metadata:
  name: elasticsearch
---

apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elasticsearch
  labels:
    logme: "true"
spec:
  version: 7.14.2
  nodeSets:
  - name: laz-local-path
    count: 1
    config:
      node.roles:
      - master
      - data
      - ingest
      node.store.allow_mmap: false
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-metricbeat.html
      xpack.monitoring.collection.enabled: true
      xpack.monitoring.elasticsearch.collection.enabled: false
    podTemplate:
      spec:
        containers:
          - name: elasticsearch
            resources:
              requests:
                memory: 512Mi
              limits:
                memory: 2Gi
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
              storage: 512Mi
        storageClassName: local-path

  http:
    tls:
      selfSignedCertificate:
        disabled: true
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data
  namespace: elasticsearch
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /cluster/elasticsearch-data
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/client-body-buffer-size: 4M
  labels:
    use-http01-solver: "true"
  name: elasticsearch-ingress
  namespace: elasticsearch
spec:
  ingressClassName: nginx
  rules:
    - host: "laz.dzervas.gr"
      http:
        paths:
          - path: /elastic(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: elasticsearch-es-http
                port:
                  number: 9200
  tls:
    - hosts:
        - laz.dzervas.gr
      secretName: laz-dzervas-gr-cert
