---

apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elasticsearch
  labels:
    logme: "true"
spec:
  version: 7.14.2
  count: 1
  elasticsearchRef:
    name: elasticsearch
  config:
    # https://www.elastic.co/guide/en/kibana/current/monitoring-metricbeat.html
    xpack.monitoring.kibana.collection.enabled: false
    xpack.monitoring.collection.enabled: true
    # enable the UI to reflect container level CPU usage, only displays info if CPU limits are set on the monitored ES cluster
    # https://www.elastic.co/guide/en/kibana/current/monitoring-settings-kb.html
    xpack.monitoring.ui.container.elasticsearch.enabled: true
    server.publicBaseUrl: https://laz.dzervas.gr/kibana
    server.basePath: /kibana
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 1Gi
            cpu: 1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  secureSettings:
  - secretName: kibana-secret-settings
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-secret: "cert-manager/client-ca-certificate"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
  labels:
    use-http01-solver: "true"
  name: kibana-ingress
  namespace: elasticsearch
spec:
  ingressClassName: nginx
  rules:
    - host: "laz.dzervas.gr"
      http:
        paths:
          - path: /kibana(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: kibana-kb-http
                port:
                  number: 5601
  tls:
    - hosts:
        - laz.dzervas.gr
      secretName: laz-dzervas-gr-cert
