apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: blogaki-smtp
  namespace: blogaki-stg
spec:
  encryptedData:
    password: AgAJif3zfnGEeJlQIS1G+xwN4XfNndnplAzOBSiy3E8iTH1m3DyChmlZqYMgrE92TfpMfKym5LsFrCw+Fl5cetN5vFXyzAhXCFvRBII4QdipUCxnZM9/2PB2JhNcK4QkhDNYqB1BQp4no3WnN+w+UGUdfiwixQVLv0tVAjcLNiCYS8cfHRfBu37GjDAodqEh2U9bfMNJUemN0DfBu9ruyaI9pKSq6j/v6uy6K6P+jXuYZszxNVKXmlGhnp/alJ9S23kvbbKHgC9+YtOOz1XCpUkvhUXS1IS6M8xDFog6nKav33LtZ+2R8C6TrQLuj9301xSwxAG6W+GWfcmHsm3kCrben5UuywD4ZNiZvvyAUFdhAYN8a9jG0UIVYZYa32yhTGt+5lvqnLyu2VfuBYoEWdSXloZHI4vWoizL+FTZ0670gQaas1iJ0ucznnHYRTFyLw+o8iVao280rTUgXpyvidcy7Yy7jfeXUM8GbEhlW5Wr1ktymvdYZeRA+CsA+xhiuEco1Nv2hBUq0sANW74bbSxOHVrzOpRSKx3IXMuMEy3LKOkopb/ItWHVStzt5sYx0xbK4UzK3pGQRKyu1x+IWp8D/NSfD5ICoJb6SSFxRPYHJZ6G9tlO78J+jlmBfbaD/5Th8d0Kq7dnzBnmBpN4VobR2+C6/C/bJ21RTBlSjay1rw4eZoZ3XVWhvkJe/wVUUZpEt332sunlz7vc0vBO6cqRINVyRHtG9ExjdAAtiCHomrtVmEN7tOJAnJ5MjA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: blogaki-smtp
      namespace: blogaki-stg
    type: Opaque

