---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: blogs-data
  namespace: blogaki-stg
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /blogs

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blogs-data
  namespace: blogaki-stg
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: blogs-data
status:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
