---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: mongodb
  namespace: kube-system
  labels:
    logme: "true"
spec:
  chart: mongodb
  repo: https://charts.bitnami.com/bitnami
  version: 11.1.1
  targetNamespace: blogaki-stg
  valuesContent: |-
    # TODO: Make replicaset work
    # architecture: replicaset
    # rbac:
      # create: true
    # serviceAccount:
      # create: true
    # pdb:
      # create: true
    # metrics:
      # enabled: true
      # serviceMonitor:
        # enabled: true
    clusterDomain: staging.blogaki.io
    disableJavascript: true
    # image:
      # debug: true
    peristence:
      storageClass: longhorn
      size: 20Gi
    service:
      nameOverride: mongodb
    auth:
      databases:
        - blogaki
      usernames:
        - blogaki
      existingSecret: mongodb-secrets

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: memcached
  namespace: kube-system
  labels:
    logme: "true"
spec:
  chart: memcached
  repo: https://charts.bitnami.com/bitnami
  version: 6.0.5
  targetNamespace: blogaki-stg
  valuesContent: |-
    # metrics:
      # enabled: true
      # serviceMonitor:
        # enabled: true
