version: '3'

services:
  traefik:
    image: traefik
    restart: unless-stopped
    networks:
      - default
      - proxy
    command:
      - "--log.level=DEBUG"
      - "--api"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls"
      - "--entrypoints.websecure.http.tls.certresolver=lan"
      - "--certificatesresolvers.lan.acme.dnschallenge"
      - "--certificatesresolvers.lan.acme.dnschallenge.provider=acme-dns"
      - "--certificatesresolvers.lan.acme.dnschallenge.resolvers=1.1.1.1"
      - "--certificatesresolvers.lan.acme.email=${EMAIL}"
      - "--certificatesresolvers.lan.acme.storage=/letsencrypt/acme.json"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data/certs:/letsencrypt
    environment:
      ACME_DNS_API_BASE: http://acmedns
      ACME_DNS_STORAGE_PATH: /letsencrypt/acme-dns
    labels:
      # Expose the Dashboard
      traefik.enable: true
      traefik.http.routers.traefik.rule: "Host(`proxy.${DOMAIN}`)"
      traefik.http.routers.traefik.entrypoints: websecure
      traefik.http.routers.traefik.service: api@internal
      # Password protection
      #traefik.http.routers.traefik.middlewares: traefik-auth
      #traefik.http.middlewares.traefik-auth.basicauth.users: "admin:$$apr1$$iNdRs1II$$Qdw59WFY6y0Oaf0JaZTip0"

      # To expose anothe container add labels:
      #traefik.enable: true
      #traefik.http.routers.<name>.rule: "Host(`<name>.${DOMAIN}`)"
      #traefik.http.routers.<name>.entrypoints: https
      #Optional port:
      #traefik.http.services.whoami.loadbalancer.server.port: <port>

  acmedns:
    image: joohoi/acme-dns
    restart: unless-stopped
    ports:
      - "53:53"
      - "53:53/udp"
    volumes:
      - /data/proxy/acme-dns.cfg:/etc/acme-dns/config.cfg:ro
      - /data/proxy/acme-dns/:/var/lib/acme-dns/

  heimdall:
    image: linuxserver/heimdall
    restart: unless-stopped
    environment:
      TZ: "${TZ}"
    volumes:
      - /data/proxy/heimdall:/config
    expose:
      - 80
    labels:
      traefik.enable: true
      traefik.http.routers.heimdall.rule: "Host(`${DOMAIN}`)"
      traefik.http.routers.heimdall.entrypoints: websecure

networks:
  proxy:
    external:
      name: proxy
