version: '3'

services:
  traefik:
    image: traefik
    restart: unless-stopped
    networks:
      - default
      - proxy
    command:
      # Due to authelia, the following exposes sensitive logs!!
      #- "--log.level=DEBUG"
      - "--log.format=json"
      - "--api"
      - "--ping=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls"
      - "--entrypoints.websecure.http.tls.certresolver=lan"
      - "--certificatesresolvers.lan.acme.dnschallenge"
      - "--certificatesresolvers.lan.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.lan.acme.dnschallenge.resolvers=1.1.1.1"
      - "--certificatesresolvers.lan.acme.email=${HOMELAB_EMAIL}"
      - "--certificatesresolvers.lan.acme.storage=/letsencrypt/acme.json"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data/certs:/letsencrypt
    healthcheck:
      test: ["CMD-SHELL", "traefik healthcheck --ping"]
      interval: 10s
      timeout: 10s
      retries: 6
    environment:
      # Requires:
       CF_DNS_API_TOKEN: "${CF_DNS_API_TOKEN}"
    labels:
      # Expose the Dashboard
      traefik.enable: true
      traefik.http.routers.traefik.rule: "Host(`proxy.${HOMELAB_DOMAIN}`)"
      traefik.http.routers.traefik.entrypoints: websecure
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.middlewares: authelia@docker

      # To expose another container add labels:
      #traefik.enable: true
      #traefik.http.routers.<name>.rule: "Host(`<name>.${HOMELAB_DOMAIN}`)"
      #traefik.http.routers.<name>.entrypoints: websecure
      # Require authentication
      #traefik.http.routers.<name>.middlewares: authelia@docker
      # Service port (optional):
      #traefik.http.services.<name>.loadbalancer.server.port: <port>

  heimdall:
    image: linuxserver/heimdall
    restart: unless-stopped
    networks:
      - proxy
    environment:
      TZ: "${HOMELAB_TZ}"
    volumes:
      - /data/proxy/heimdall:/config
    expose:
      - 80
    labels:
      traefik.enable: true
      traefik.http.routers.heimdall.rule: "Host(`${HOMELAB_DOMAIN}`)"
      traefik.http.routers.heimdall.entrypoints: websecure
      traefik.http.routers.heimdall.middlewares: authelia@docker

networks:
  proxy:
    external:
      name: proxy
