---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager-helmchart
  namespace: kube-system
spec:
  chart: cert-manager
  repo: https://charts.jetstack.io
  targetNamespace: cert-manager
  valuesContent: |-
    installCRDs: true
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
  namespace: cert-manager
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: dzervas+laz@dzervas.gr
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cert-manager-cluster-issuer-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
      selector:
        matchLabels:
          "use-http01-solver": "true"
    - dns01:
        cloudflare:
          email: dzervas+laz@dzervas.gr
          apiTokenSecretRef:
            name: cert-manager-cloudflare-api-token
            key: api-token
      selector:
        dnsNames:
        - dzerv.it
        - "*.dzerv.it"

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: client-ca
  namespace: cert-manager
spec:
  secretName: client-ca-certificate
  dnsNames:
    - laz.dzervas.gr
    - "*.laz.dzervas.gr"
  subject:
    organizations:
      - homelab
  duration: 87658h # 10 years
  privateKey:
    algorithm: ECDSA
    size: 384
  isCA: true

  issuerRef:
    name: selfsigned
    kind: ClusterIssuer

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: client-ca
spec:
  ca:
    secretName: client-ca-certificate

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: client-desktop
spec:
  secretName: client-desktop-certificate
  dnsNames:
    - laz.dzervas.gr
    - "*.laz.dzervas.gr"
  isCA: false
  duration: 87658h # 10 years
  privateKey:
    algorithm: ECDSA
    size: 384
  usages:
    - server auth
    - client auth

  issuerRef:
    name: client-ca
    kind: Issuer
