---
apiVersion: v1
kind: Namespace
metadata:
  name: descheduler

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: descheduler
  namespace: kube-system
  labels:
    logme: "true"
spec:
  chart: descheduler
  repo: https://kubernetes-sigs.github.io/descheduler/
  version: 0.26.0
  targetNamespace: descheduler
