apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  name: cliproxyapi-netbird-test
  namespace: cliproxyapi
spec:
  hostnames:
    - ai.vpn.dzerv.art
  parentRefs:
    - name: netbird
      namespace: netbird
  rules:
    - backendRefs:
      - name: cliproxyapi
        port: 8317
