---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx-helmchart
  namespace: kube-system
spec:
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  targetNamespace: ingress
  valuesContent: |-
    controller:
      replicaCount: 2
      # service:
        # ports:
          # http: 9080
          # https: 9443
