---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: kube-system
  labels:
    logme: "true"
spec:
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  version: 4.7.1
  targetNamespace: ingress
  valuesContent: |-
    tcp:
      2222: "borgserver/borgserver-service:2222"
    controller:
      replicaCount: 2
      watchIngressWithoutClass: true
      ingressClassResource:
        default: true
