---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 7.9.0
  nodeSets:
  - name: laz
    count: 1
    config:
      node.roles:
      - master
      - data
      - ingest
      node.store.allow_mmap: false
    podTemplate:
      # metadata:
        # labels:
          # foo: bar
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 1700Mi
              cpu: 0.9
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms1g -Xmx1g"
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
              storage: 512Mi
        storageClassName: standard

  http:
    service:
      spec:
        type: ClusterIP

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /cluster/elasticsearch-data

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: elasticsearch-ingress
spec:
  rules:
  - host: laz.dzervas.gr
    http:
      paths:
      - path: /elastic
        backend:
          serviceName: elasticsearch-es-http
          servicePort: 9200

---

apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 7.9.0
  count: 1
  elasticsearchRef:
    name: elasticsearch
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 1Gi
            cpu: 0.3
  secureSettings:
  - secretName: kibana-secret-settings

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kibana-ingress
spec:
  rules:
  - host: laz.dzervas.gr
    http:
      paths:
      - path: /kibana
        backend:
          serviceName: kibana-kb-http
          servicePort: 5601

---

apiVersion: v1
kind: Secret
metadata:
  name: kibana-kibana-secret-config
type: Opaque
data:
  xpack.security.encryptionKey: 3l3hTUNg1hxrhMN8RDy3nM5MgIAP4u5OKAslEMsygJc=

---
