---
apiVersion: v1
kind: Namespace
metadata:
  name: kured

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kured-helmchart
  namespace: kube-system
  labels:
    logme: "true"
spec:
  chart: kured
  repo: https://kubereboot.github.io/charts
  version: 4.4.1
  targetNamespace: kured
