---
apiVersion: v1
kind: Namespace
metadata:
  name: kured

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kured-helmchart
  namespace: kube-system
  labels:
    logme: "true"
spec:
  chart: kured
  repo: https://weaveworks.github.io/kured
  version: 2.12.0
  targetNamespace: kured
