---

- hosts: server
  become: yes
  vars_files: ~/.homelab/server.yml
  roles:
    - role: vector
      vars:
        add_vector_docker_group: yes
        add_vector_journal_group: yes
        sources:
          journald:
            type: journald
            current_boot_only: true
          docker:
            type: docker
        transforms:
          json:
            type: json_parser
            inputs: "{{ sources.keys() | list }}"
            drop_invalid: false
        sinks:
          http:
            type: http
            uri: "https://vector.{{ homelab_domain }}"
            inputs: ["json"]
            encoding.codec: json

- hosts: router
  vars_files: ~/.homelab/server.yml
  become: yes
  roles:
    - role: vector
      vars:
        sources:
          file:
            type: file
            ignore_older: 86400
            files:
              - /var/log/messages
              - /var/log/daemon.log
        sinks:
          http:
            type: http
            uri: "https://vector.{{ homelab_domain }}"
            inputs: "{{ sources.keys() | list }}"
            encoding.codec: json

- hosts: proxy
  vars_files: ~/.homelab/server.yml
  become: yes
  roles:
    - role: vector
      vars:
        add_vector_journal_group: yes
        sources:
          journal:
            type: journald
            current_boot_only: true
        sinks:
          http:
            type: http
            uri: "https://vector.{{ homelab_domain }}"
            inputs: "{{ sources.keys() | list }}"
            encoding.codec: json
