---
apiVersion: v1
kind: Namespace
metadata:
  name: minecraft

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: minecraft
  namespace: kube-system
  labels:
    logme: "true"
spec:
  chart: minecraft
  repo: https://itzg.github.io/minecraft-server-charts/
  version: 4.7.4
  targetNamespace: minecraft
  valuesContent: |-
    persistence:
      storageClass: longhorn
      dataDir:
        enabled: true
    minecraftServer:
      serviceType: LoadBalancer
      eula: "TRUE"
      ops: dzervasgr,looselyrigorous
      whitelist: dzervasgr,looselyrigorous,CHINESIUM_
      difficulty: hard
      motd: Deep Rock MineCraft
      pvp: true

      version: 1.19.2
      # version: LATEST
      type: FABRIC
      # type: VANILLA
      jvmOpts: "-Dowo.handshake.disable=true"

      modrinth:
        projects:
          - cc-restitched
          - modern-industrialization
          - cloth-config
          - fabric-api
          - owo-lib
        optionalDependencies: true

      # cfServerMod: cc-restitched,modern-industrialization
      # autoCurseForge:
        # apiKey:
          # existingSecret: minecraft-curseforge-secret
          # secretKey: cf-api-key
        # slug: modern-industrialization
        # includeMods:
          # - cc-tweaked
          # - cc-restitched
          # - modern-industrialization
