---
apiVersion: v1
kind: Namespace
metadata:
  name: openebs

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: openebs-helmchart
  namespace: kube-system
  labels:
    logme: "true"
spec:
  chart: openebs
  repo: https://openebs.github.io/charts
  version: 3.8.0
  targetNamespace: openebs
  valuesContent: |-
    legacy:
      enabled: false
    localprovisioner:
      enabled: false
      hostpathclass
        enabled: false
      deviceclass:
        enabled: false

    openebs-ndm:
      enabled: true
    cstor:
      enabled: true
