---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operatorequals
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operatorequals
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: operatorequals
    namespace: kube-system
