---

- hosts: proxy
  vars_files: ~/.homelab/server.yml
  become: yes
  roles:
    - role: vector
      vars:
        vector_nightly: yes
        add_vector_journal_group: yes
        sources:
          journal:
            type: journald
            current_boot_only: true
        sinks:
          http:
            type: http
            uri: "https://vector.{{ homelab_domain }}"
            inputs: "{{ sources.keys() | list }}"
            encoding.codec: ndjson
