---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: sealed-secrets-controller
  namespace: kube-system
spec:
  chart: sealed-secrets
  repo: https://charts.helm.sh/stable
  targetNamespace: kube-system
