config:
  snipeit:
    url: https://stock.dzerv.art
    timezone: Europe/Athens
    key: "base64:z54akAQPx9M8x5TTnUp+j2Sh62oDl9/3W8+ZY02TWcc="
    # envConfig:
    # DB_CONNECTION: sqlite
mysql:
  enabled: true
  persistence:
    enabled: true
    storageClass: longhorn
    size: 5Gi
persistence:
  enabled: true
  storageClass: longhorn
  size: 1Gi
# extraVolumeMounts:
#   - name: data
#     mountPath: /var/www/html/database/database.sqlite
#     subPath: database.sqlite

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-secret: "cert-manager/client-ca-certificate"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
  path: /
  pathType: Prefix
  hosts:
    - stock.dzerv.art
  tls:
    - hosts:
        - stock.dzerv.art
      secretName: stock-dzerv-art-cert
