---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik-ingress-helmchart
  namespace: kube-system
spec:
  chart: traefik
  repo: https://helm.traefik.io/traefik
  targetNamespace: ingress
  valuesContent: |-
    logs:
      general:
        level: INFO
    additionalArguments:
      - --certificatesresolvers.letsencrypt.acme.email=dzervas+laz@dzervas.gr
      - --certificatesresolvers.letsencrypt.acme.storage=/certs/acme.json
      - --certificatesresolvers.letsencrypt.acme.tlschallenge
      - --certificatesresolvers.letsencrypt.acme.httpchallenge
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.cloudflare.acme.dnschallenge
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1
      - --certificatesresolvers.cloudflare.acme.email=dzervas+laz@dzervas.gr
      - --certificatesresolvers.cloudflare.acme.storage=/certs/acme-cloudflare.json
    ports:
      traefik:
        exposed: true
      web:
        exposedPort: 80
        redirectTo: websecure
      websecure:
        exposedPort: 443
        tls:
          enabled: true
          certResolver: letsencrypt
    persistence:
      enabled: true
      name: certs
      path: /certs
    env:
      - name: CLOUDFLARE_DNS_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: traefik-cloudflare-api-token
            key: CLOUDFLARE_DNS_API_TOKEN
