---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik-ingress-helmchart
  namespace: kube-system
spec:
  chart: traefik
  repo: https://helm.traefik.io/traefik
  targetNamespace: ingress
  valuesContent: |-
    logs:
      general:
        level: INFO
    additionalArguments:
      - --certificatesresolvers.letsencrypt.acme.email=dzervas+laz@dzervas.gr
      - --certificatesresolvers.letsencrypt.acme.storage=/certs/acme.json
      - --certificatesresolvers.letsencrypt.acme.tlschallenge
      - --certificatesresolvers.letsencrypt.acme.httpchallenge
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
    ports:
      traefik:
        exposed: true
      web:
        exposedPort: 80
        redirectTo: websecure
      websecure:
        exposedPort: 443
        tls:
          enabled: true
          certResolver: letsencrypt
    persistence:
      enabled: true
      name: certs
      path: /certs
