---
apiVersion: v1
kind: Namespace
metadata:
  name: zabbix

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: zabbix
  namespace: kube-system
  labels:
    logme: "true"
spec:
  chart: zabbix
  repo: https://zabbix-community.github.io/helm-zabbix
  version: 3.4.4
  targetNamespace: zabbix
  valuesContent: |-
    postgresql:
      persistence:
        enabled: true
        storage_class: longhorn
    zabbixproxy:
      enabled: true
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: monitor.k8s.dzervas.gr
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - monitor.k8s.dzervas.gr
          secretName: monitor-k8s-dzervas-gr-cert
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
        nginx.ingress.kubernetes.io/auth-tls-secret: "cert-manager/client-ca-certificate"
        nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"

