---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-prometheus-data
  namespace: grafana
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /cluster/grafana-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-prometheus-data
  namespace: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: grafana-prometheus-data
status:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
