---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: prometheus-helmchart
  namespace: kube-system
spec:
  chart: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  targetNamespace: monitoring
  version: 45.0.0
  valuesContent: |-
    grafana:
      defaultDashboardsTimezone: Europe/Athens
      persistence:
        enabled: true
        existingClaim: grafana-prometheus-data
      grafana.ini:
        server:
          domain: monitor.k8s.dzervas.gr
          root_url: https://monitor.k8s.dzervas.gr/graphs
          serve_from_sub_path: true
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
          nginx.ingress.kubernetes.io/auth-tls-secret: "cert-manager/client-ca-certificate"
          nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
        hosts:
          - monitor.k8s.dzervas.gr
        pathType: Prefix
        paths:
          - /graphs(/|$)(.*)
        path: /graphs
        tls:
          - hosts:
              - monitor.k8s.dzervas.gr
            secretName: monitor-k8s-dzervas-gr-cert

    alertmanager:
      enabled: false

    prometheus:
      prometheusSpec:
        routePrefix: /prometheus
        serviceMonitorSelectorNilUsesHelmValues: false
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
          nginx.ingress.kubernetes.io/auth-tls-secret: "cert-manager/client-ca-certificate"
          nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
        hosts:
          - monitor.k8s.dzervas.gr
        pathType: Prefix
        paths:
          - /prometheus(/|$)(.*)
        path: /prometheus
        tls:
          - hosts:
              - monitor.k8s.dzervas.gr
            secretName: monitor-k8s-dzervas-gr-cert

    prometheusOperator:
      tls:
        enabled: false
      # admissionWebhooks:
        # certManager:
          # enabled: true
          # issuerRef:
            # name: letsencrypt
            # kind: ClusterIssuer
