---
apiVersion: v1
kind: Namespace
metadata:
  name: borgserver

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: borgserver
  namespace: kube-system
  labels:
    logme: "true"
spec:
  chart: borgserver
  repo: https://dzervas.github.io/docker-borgserver/
  version: 1.2.6-0
  targetNamespace: borgserver
  valuesContent: |-
    borg:
      useKeysSecret: true
    persistence:
      size: 180Gi
      storageClass: longhorn
    # replicaCount: 2
    nodeSelector:
      kubernetes.io/hostname: "gr0.dzerv.art"
    clients:
      - name: dzervas-desktop
        restrictToPaths:
          - /backup/dzervas-desktop
        type: ssh-ed25519
        key: AAAAC3NzaC1lZDI1NTE5AAAAICS1ajO167YXmPzlWZT6+ydcO359SW1BljPK/GgBijHZ
      - name: dzervas-hass
        restrictToPaths:
          - /backup/dzervas-hass
        type: ssh-ed25519
        key: AAAAC3NzaC1lZDI1NTE5AAAAIHYF2FfOQAsVsdR0+ya3iXiDjklWHdMAfWt31uXMz6rE
