version: '3.7'

services:
  octoprint:
    #image: nunofgs/octoprint
    build: .
    restart: unless-stopped
    networks:
      - proxy
    devices:
      - /dev/ttyUSB0
      - /dev/video0
    volumes:
      - /data/3dprinter/octoprint:/data
    environment:
      MJPEG_STREAMER_INPUT: "-n -r 800x600 -f 25"
      TZ: "${HOMELAB_TZ}"
    labels:
      traefik.enable: true
      traefik.http.routers.3dprinter.rule: "Host(`3dprinter.${HOMELAB_DOMAIN}`)"
      traefik.http.routers.3dprinter.entrypoints: websecure
      traefik.http.routers.3dprinter.middlewares: authelia@docker

networks:
  proxy:
    external:
      name: proxy
