version: '3.7'

services:
  octoprint:
    #image: nunofgs/octoprint
    build: .
    restart: unless-stopped
    networks:
      - proxy
    devices:
      - /dev/ttyUSB.Ender-3
      #- /dev/video0
      #- /tmp/printer
    volumes:
      # chown 1000:1000 -R /data/3dprinter/octoprint/
      - /data/3dprinter/octoprint:/data
      #- /data/3dprinter/octoprint:/home/octoprint/.octoprint
      #- /data/3dprinter/printer.cfg:/printer.cfg
    environment:
      MJPEG_STREAMER_INPUT: "-r 800x600 -f 25"
      TZ: "${HOMELAB_TZ}"
    labels:
      traefik.enable: true
      traefik.http.routers.3dprinter.rule: "Host(`3dprinter.${HOMELAB_DOMAIN}`)"
      traefik.http.routers.3dprinter.entrypoints: websecure
      traefik.http.routers.3dprinter.middlewares: authelia@docker

networks:
  proxy:
    external:
      name: proxy
