---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: grafana-helmchart
  namespace: kube-system
  labels:
    logme: "true"
spec:
  chart: grafana
  repo: https://grafana.github.io/helm-charts
  version: 6.55.0
  targetNamespace: grafana
  valuesContent: |-
    rbac:
      namespaced: true

    persistence:
      enabled: true
      storageClassName: longhorn

    grafana.ini:
      server:
        domain: grafana.k8s.dzervas.gr
        root_url: https://grafana.k8s.dzervas.gr/
        #serve_from_sub_path: true

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
        nginx.ingress.kubernetes.io/auth-tls-secret: "cert-manager/client-ca-certificate"
        nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
      hosts:
        - grafana.k8s.dzervas.gr
      tls:
        - hosts:
            - grafana.k8s.dzervas.gr
          secretName: grafana-k8s-dzervas-gr-cert

    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Mimir
            type: prometheus
            url: http://grafana-mimir-helmchart-nginx/prometheus
          - name: Loki
            type: loki
            url: http://grafana-loki-helmchart:3100
