---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: grafana
  namespace: kube-system
  labels:
    logme: "true"
spec:
  chart: grafana
  repo: https://grafana.github.io/helm-charts
  version: 6.58.9
  targetNamespace: grafana
  valuesContent: |-
    rbac:
      namespaced: true
    persistence:
      enabled: true
      storageClassName: longhorn
    grafana.ini:
      users:
        allow_sign_up: false

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
        nginx.ingress.kubernetes.io/auth-tls-secret: "cert-manager/client-ca-certificate"
        nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
        nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-WEBAUTH-USER admin;
        nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
      hosts:
        - grafana.dzerv.art
      tls:
        - hosts:
            - grafana.dzerv.art
          secretName: grafana-dzerv-art-cert
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Mimir
            type: prometheus
            url: http://mimir-nginx/prometheus
            jsonData:
              httpHeaderName1: 'X-Scope-OrgID'
            secureJsonData:
              httpHeaderValue1: 'metamonitoring'
          - name: Loki
            type: loki
            url: http://loki-gateway
