---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: grafana-loki-helmchart
  namespace: kube-system
  labels:
    logme: "true"
spec:
  chart: loki-stack
  repo: https://grafana.github.io/helm-charts
  version: 2.9.10
  targetNamespace: grafana
