---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: grafana-loki-helmchart
  namespace: kube-system
  labels:
    logme: "true"
spec:
  chart: loki
  repo: https://grafana.github.io/helm-charts
  version:
  targetNamespace: grafana
  valuesContent: |-
    selfMonitoring:
      enabled: false

    storage:
      type: filesystem

    write:
      replicas: 2
      persistence:
        storageClass: longhorn
    read:
      replicas: 2
      persistence:
        storageClass: longhorn
    backend:
      replicas: 2
      persistence:
        storageClass: longhorn
