apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: mimir
  namespace: kube-system
  labels:
    logme: "true"
spec:
  chart: mimir-distributed
  repo: https://grafana.github.io/helm-charts
  version: 4.3.1
  targetNamespace: grafana
  valuesContent: |-
    mimir:
      structuredConfig:
        blocks_storage:
          backend: filesystem

    minio:
      enabled: false
    alertmanager:
      enabled: false
    overrides_exporter:
      enabled: false
    query_scheduler:
      enabled: false
    ruler:
      enabled: false
    nginx:
      enabled: false

    ingester:
      persistentVolume:
        size: 20Gi
        storageClass: longhorn
    store_gateway:
      persistentVolume:
        storageClass: longhorn
    compactor:
      persistentVolume:
        storageClass: longhorn

    nginx:
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
          nginx.ingress.kubernetes.io/auth-tls-secret: "cert-manager/client-ca-certificate"
          nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
        hosts:
          - host: metrics.dzerv.art
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - metrics.dzerv.art
            secretName: metrics-dzerv-art-cert

    metaMonitoring:
      dashboards:
        enabled: true
      serviceMonitor:
        enabled: true
      grafanaAgent:
        enabled: true
