# /var/lib/rancher/rke2/server/manifests/rke2-coredns-config.yaml
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-coredns
  namespace: kube-system
spec:
  valuesContent: |-
    nodelocal:
      enabled: false

    servers:
      - zones:
          - zone: .
            use_tcp: true
        port: 5353
        plugins:
          - name: template
            parameters: IN A kube.vpn.dzerv.art
            configBlock: |-
              match ^kube\.vpn\.dzerv\.art\.$
              answer "{{ .Name }} 60 IN A 10.43.0.1"
              fallthrough
          - name: template
            parameters: IN A vpn.dzerv.art
            configBlock: |-
              match ^.+\.vpn\.dzerv\.art\.$
              answer "{{ .Name }} 60 IN A 10.43.0.50"
              fallthrough
          - name: forward
            # AdGuard public DNS
            parameters: . tls://94.140.14.14 tls://94.140.15.15
            configBlock: |-
              tls_servername dns.adguard-dns.com

      - zones:
          - zone: .
            use_tcp: true
        port: 53
        plugins:
          - name: errors
          - name: health
            configBlock: lameduck 10s
          - name: ready
          - name: rewrite
            parameters: name exact git.vpn.dzerv.art traefik.traefik.svc.cluster.local answer auto
          - name: kubernetes
            parameters: in-addr.arpa ip6.arpa
            configBlock: |-
              pods insecure
              fallthrough in-addr.arpa ip6.arpa
              ttl 30
          - name: prometheus
            parameters: 0.0.0.0:9153
          - name: forward
            parameters: . /etc/resolv.conf
          - name: cache
            parameters: 30
          - name: loop
          - name: reload
          - name: loadbalance

    prometheus:
      service:
        enabled: true
      monitor:
        enabled: true
---
apiVersion: v1
kind: Service
metadata:
  name: vpn-dns
  namespace: kube-system
spec:
  clusterIP: 10.43.0.53
  selector:
    app.kubernetes.io/instance: rke2-coredns
    app.kubernetes.io/name: rke2-coredns
    k8s-app: kube-dns
  ports:
    - name: udp-53
      port: 53
      protocol: UDP
      targetPort: 5353
    - name: tcp-53
      port: 53
      protocol: TCP
      targetPort: 5353
