version: '3'

services:
  hass:
    depends_on:
      - mqtt
    image: homeassistant/home-assistant:stable
    restart: unless-stopped
    networks:
      - default
      - proxy
    volumes:
      - /data/hass/hass:/config
    ports:
      - 51827:51827
    expose:
      - 8123
    environment:
      TZ: "${TZ}"
    labels:
      traefik.enable: true
      traefik.http.routers.hass.rule: "Host(`hass.${HOMELAB_DOMAIN}`)"
      traefik.http.routers.hass.entrypoints: websecure

  mqtt:
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes:
      - /data/hass/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - /data/hass/mqtt:/mosquitto/data

networks:
  proxy:
    external:
      name: proxy
