# Managed by Ansible

table filter {
	chain INPUT {
		policy DROP;

		# connection tracking
		mod state state INVALID DROP;
		mod state state (ESTABLISHED RELATED) ACCEPT;

		# allow local packet
		interface lo ACCEPT;

		# respond to ping
		proto icmp ACCEPT;
		# SSH from everywhere
		proto tcp dport ssh ACCEPT;

		# DNS on all subnets
		interface ({{ subnets | json_query("[].iface") | join(" ") }}) proto (tcp udp) dport domain ACCEPT;
		# DHCP on some subnets
		interface ({{ subnets | json_query("[?dhcp == 'true'].iface") | join(" ") }}) proto udp dport bootps ACCEPT;
	}

	chain OUTPUT {
		policy ACCEPT;

		# connection tracking
		mod state state INVALID DROP;
		mod state state (ESTABLISHED RELATED) ACCEPT;
	}

	chain FORWARD {
		policy DROP;

		# connection tracking
		mod state state INVALID DROP;
		mod state state (ESTABLISHED RELATED) ACCEPT;

		# Allow internet on some interfaces
		interface ({{ subnets | json_query("[?allow_internet == 'true'].iface") | join(" ") }}) outerface {{ wan_iface }} ACCEPT;
	}
}

table nat {
	chain POSTROUTING {
		# Masquerade internet access - NAT
		saddr ({{ subnets | json_query("[?allow_internet == 'true'].cidr") | join(" ") }}) outerface {{ wan_iface }} MASQUERADE;
	}
}
