driver={{ hostapd_driver }}

logger_syslog=8
logger_syslog_level=3
logger_stdout=8
logger_stdout_level=3

ctrl_interface=/var/run/hostapd
ctrl_interface_group=sudo

# Operation mode (a = IEEE 802.11a (5 GHz), b = IEEE 802.11b (2.4 GHz),
# g = IEEE 802.11g (2.4 GHz), ad = IEEE 802.11ad (60 GHz); a/g options are used
# with IEEE 802.11n (HT), too, to specify band). For IEEE 802.11ac (VHT), this
# needs to be set to hw_mode=a.
hw_mode={{ hostapd_mode }}
channel={{ hostapd_channel }}
country_code={{ hostapd_country_code }}

ieee80211d={{ hostapd_80211d | int }}
ieee80211h={{ hostapd_80211h | int }}
ieee80211n={{ hostapd_80211n | int }}
ieee80211w={{ hostapd_80211w | int }}
ieee80211ac={{ hostapd_80211ac | int }}
ieee80211ax={{ hostapd_80211ax | int }}

beacon_int=100
auth_algs=1 # PSK

wmm_enabled={{ hostapd_wmm_enabled | int }}
require_ht={{ hostapd_require_ht | int }}
require_vht={{ hostapd_require_vht | int }}

{% if hostapd_vht_oper_chwidth is defined %}hostapd_vht_oper_chwidth={{ hostapd_vht_oper_chwidth }}{% endif %}
{% if hostapd_vht_oper_centr_freq_seg0_idx is defined %}hostapd_vht_oper_centr_freq_seg0_idx={{ hostapd_vht_oper_centr_freq_seg0_idx }}{% endif %}
{% if hostapd_vht_oper_centr_freq_seg1_idx is defined %}hostapd_vht_oper_centr_freq_seg1_idx={{ hostapd_vht_oper_centr_freq_seg1_idx }}{% endif %}
{% if hostapd_ht_capab is defined %}hostapd_ht_capab={{ hostapd_ht_capab }}{% endif %}
{% if hostapd_vht_capab is defined %}hostapd_vht_capab={{ hostapd_vht_capab }}{% endif %}

# Network configuration

{% for subnet in subnets if "wifi_ssid" in subnet -%}
	# {{ ssid }} -> {{ subnet.iface }}
	{% set wifi_iface_index = (subnets | json_query("[?wifi_iface=='" + subnet.wifi_iface + "'].wifi_ssid")).index(subnet.wifi_ssid) %}

	{% if wifi_iface_index == 0 -%}
		interface={{ interface }}
	{% else %}
		bss={{ interface }}_{{ wifi_iface_index }}
	{% endif -%}

	ssid2="{{ subnet.wifi_ssid }}"
	wpa=2
	wpa_passphrase={{ subnet.wifi_passphrase }}
	wpa_key_mgmt=WPA-PSK
	rsn_pairwise=CCMP
	bridge={{ subnet.iface }}
	ignore_broadcast_ssid={{ config.hidden | int }}
{%- endor %}
