---
- name: Generate WireGuard private key
  command: wg genkey
  args:
    creates: /etc/wireguard/privatekey
  register: wg_genkey
  notify: Restart WireGuard service

- name: Save private key to file
  copy:
    content: "{{ wg_genkey.stdout }}"
    dest: /etc/wireguard/privatekey
    owner: root
    group: root
    mode: '0600'
  when: wg_genkey.changed

- name: Generate WireGuard public key
  shell: echo "{{ wg_genkey.stdout }}" | wg pubkey
  when: wg_genkey.changed
  register: wg_pubkey
  notify: Restart WireGuard service

- name: Save public key to file
  copy:
    content: "{{ wg_pubkey.stdout }}"
    dest: /etc/wireguard/publickey
    owner: root
    group: root
    mode: '0644'
  when: wg_pubkey.changed

- name: Slurp public key
  slurp:
    src: /etc/wireguard/publickey
  register: wireguard_public_key

- name: Slurp private key
  slurp:
    src: /etc/wireguard/privatekey
  register: wireguard_private_key

- name: Update WireGuard configuration
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: '0600'
  notify: Restart WireGuard service
