---
- import_tasks: install.yaml
- import_tasks: config.yaml

# WireGuard firewall rules are handled withing the config

- name: Start WireGuard service
  service:
    name: wg-quick@wg0.service
    state: started
    enabled: yes

- meta: flush_handlers

- name: Wait for other hosts to be reachable
  wait_for:
    host: "{{ hostvars[item].wireguard_ip }}"
    port: 22
    delay: 1
    timeout: 60
  loop: "{{ groups.all | difference([inventory_hostname]) }}"
