---
- name: Install WireGuard
  apt:
    name:
      - wireguard
      - resolvconf
    state: present

- name: Generate WireGuard private key
  command: wg genkey
  args:
    creates: /etc/wireguard/privatekey
  register: wg_genkey
  notify: Restart WireGuard service

- name: Save private key to file
  copy:
    content: "{{ wg_genkey.stdout }}"
    dest: /etc/wireguard/privatekey
    owner: root
    group: root
    mode: '0600'
  when: wg_genkey.changed

- name: Generate WireGuard public key
  shell: echo "{{ wg_genkey.stdout }}" | wg pubkey
  when: wg_genkey.changed
  register: wg_pubkey
  notify: Restart WireGuard service

- name: Save public key to file
  copy:
    content: "{{ wg_pubkey.stdout }}"
    dest: /etc/wireguard/publickey
    owner: root
    group: root
    mode: '0644'
  when: wg_pubkey.changed

- name: Slurp public key
  slurp:
    src: /etc/wireguard/publickey
  register: wireguard_public_key

- name: Slurp private key
  slurp:
    src: /etc/wireguard/privatekey
  register: wireguard_private_key

- name: Update WireGuard configuration
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: '0600'
  notify: Restart WireGuard service

- name: Allow WireGuard traffic
  iptables:
    chain: INPUT
    protocol: udp
    destination_port: 51820
    jump: ACCEPT
    state: present

- name: Open all ports on WireGuard interface
  iptables:
    chain: INPUT
    in_interface: wg0*
    jump: ACCEPT
    state: present

- name: Start WireGuard service
  service:
    name: wg-quick@wg0.service
    state: started
    enabled: yes

- meta: flush_handlers

- name: Wait for other hosts to be reachable
  wait_for:
    host: "{{ hostvars[item].wireguard_ip }}"
    port: 22
    delay: 1
    timeout: 60
  loop: "{{ groups.all | difference([inventory_hostname]) }}"
