version: '3'

services:
  watchtower:
    image: containrrr/watchtower:latest
    restart: unless-stopped
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_TIMEOUT: "30s"
      TZ: "${HOMELAB_TZ}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
