version: '3'

services:
  ouroboros:
    image: pyouroboros/ouroboros
    restart: unless-stopped
    environment:
      CLEANUP: "true"
      INTERVAL: 300
      LOG_LEVEL: info
      SELF_UPDATE: "true"
      IGNORE: 3dprinter_octoprint_1
      TZ: "${HOMELAB_TZ}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
