---
- name: Get stable Cilium CLI version
  uri:
    url: https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt
    return_content: yes
  register: cilium_cli_version_response

- name: Set Cilium CLI facts
  set_fact:
    CILIUM_CLI_VERSION: "{{ cilium_cli_version_response.content | trim }}"
    CLI_ARCH: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"

- name: Download Cilium CLI tarball
  get_url:
    url: "https://github.com/cilium/cilium-cli/releases/download/{{ CILIUM_CLI_VERSION }}/cilium-linux-{{ CLI_ARCH }}.tar.gz"
    checksum: "sha256:https://github.com/cilium/cilium-cli/releases/download/{{ CILIUM_CLI_VERSION }}/cilium-linux-{{ CLI_ARCH }}.tar.gz.sha256sum"
    dest: "/tmp/cilium-linux-{{ CLI_ARCH }}.tar.gz"
    mode: "0644"

- name: Extract Cilium CLI binary to /usr/local/bin
  become: yes
  unarchive:
    src: "/tmp/cilium-linux-{{ CLI_ARCH }}.tar.gz"
    dest: /usr/local/bin
    remote_src: yes

- name: Remove downloaded tarball and checksum file
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/cilium-linux-{{ CLI_ARCH }}.tar.gz"
    - "/tmp/cilium-linux-{{ CLI_ARCH }}.tar.gz.sha256sum"
