---
- name: Create k3s config directory
  file:
    path: /etc/rancher/k3s
    recurse: true
    state: directory

- name: Update k3s resolv.conf
  copy:
    content: "nameserver 1.1.1.1\nnameserver 1.0.0.1"
    dest: /etc/rancher/k3s/resolv.conf
  notify: Restart k3s service

# From https://docs.k3s.io/security/hardening-guide#pod-security
- name: Add pod security admissions
  copy:
    src: psa.yaml
    dest: /var/lib/rancher/k3s/server/psa.yaml
  notify: Restart k3s service

- name: Update k3s config.yaml
  template:
    src: config.yaml.j2
    dest: /etc/rancher/k3s/config.yaml
    owner: root
    group: root
    mode: "0600"
  notify: Restart k3s service

- name: K3s config check
  command: k3s check-config
  args:
    stdin_add_newline: no
  register: check
  # STATUS: pass with ansi colors
  failed_when: "(check.stdout | split('\n') | last) != '\u001b[37mSTATUS\u001b[m: \u001b[32mpass\u001b[m' or check.rc != 0"

- name: Update k3s service
  template:
    src: k3s.service.j2
    dest: /etc/systemd/system/k3s.service
  notify: Restart k3s service
