---
- name: Create k3s config directory
  file:
    path: /etc/rancher/k3s
    recurse: true
    state: directory

- name: Update k3s resolv.conf
  copy:
    content: "nameserver 1.1.1.1\nnameserver 1.0.0.1"
    dest: /etc/rancher/k3s/resolv.conf
  notify: Restart k3s service

- name: Update k3s config.yaml
  template:
    src: config.yaml.j2
    dest: /etc/rancher/k3s/config.yaml
    owner: root
    group: root
    mode: '0600'
  notify: Restart k3s service

- name: K3s config check
  command: k3s check-config

- name: Update k3s service
  template:
    src: k3s.service.j2
    dest: /etc/systemd/system/k3s.service
  notify: Restart k3s service
