---
- name: Allow k3s traffic
  ufw:
    rule: allow
    proto: "{{ item.protocol }}"
    port: "{{ item.port }}"
    interface: "{{ k3s_iface }}"
    direction: in
  loop:
    - port: "2379" # ETCD server
      protocol: tcp
    - port: "2380" # ETCD server
      protocol: tcp
    - port: "6443" # API server
      protocol: tcp
    - port: "8472" # Flannel VXLAN
      protocol: udp
    - port: "10250" # Kubelet API
      protocol: tcp
    - port: "10251" # kube-scheduler
      protocol: tcp

- name: Allow pod & service traffic (ingress)
  ufw:
    rule: allow
    from: "{{ item }}"
    to: any
  loop:
    - 10.42.0.0/16
    - 10.43.0.0/16

# - name: Allow pod & service traffic (egress)
#   ufw:
#     rule: allow
#     dest: "{{ item }}"
#     interface: "{{ k3s_iface }}"
#     direction: out
#   loop:
#     - 10.42.0.0/16
#     - 10.43.0.0/16

- name: Allow services traffic
  ufw:
    rule: allow
    proto: tcp
    port: "{{ item }}"
  loop:
    - "80"
    - "443"
    - "2222"
    - "6443"
