---
- import_tasks: download.yaml
- import_tasks: multipathd.yaml
- import_tasks: config.yaml

# Make sure that the master has started to create the agent-token
- meta: flush_handlers
  when:
    - inventory_hostname in groups.master
    - k3s_init is defined
    - k3s_init

- import_tasks: agent-token.yaml
- import_tasks: firewall.yaml
  tags: firewall

- name: Start k3s
  service:
    name: k3s
    state: started
    enabled: yes
    daemon_reload: yes
