---
- import_tasks: download.yaml
- import_tasks: multipathd.yaml
- import_tasks: config.yaml
- import_tasks: wireguard.yaml
  tags:
    - wireguard

# Make sure that the master has started to create the agent-token
- meta: flush_handlers
  when:
    - inventory_hostname in groups.master
    - k3s_init is defined
    - k3s_init

- import_tasks: agent-token.yaml
- import_tasks: firewall.yaml
  tags: firewall

- name: Add GHCR credentials
  template:
    src: registries.yaml.j2
    dest: /etc/rancher/k3s/registries.yaml
    owner: root
    group: root
    mode: "0600"
  tags:
    - k3s
    - k3s-registry

- name: Start k3s
  service:
    name: k3s
    state: started
    enabled: yes
    daemon_reload: yes
