---
- name: Install multipath-tools
  package:
    name: multipath-tools
    state: present

- name: Update multipath.conf
  copy:
    src: multipath.conf
    dest: /etc/multipath.conf
  notify: Restart multipathd service

- name: Start multipathd service
  service:
    name: multipathd
    state: started
    enabled: yes
