---
- name: journald max log total size
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: ^SystemMaxUse=
    line: SystemMaxUse=2G
  notify: Restart journald service

- name: journald max log file size
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: ^SystemMaxFileSize=
    line: SystemMaxFileSize=100M
  notify: Restart journald service

- name: Overwrite .bashrc for the target user
  copy:
    src: .bashrc
    dest: "{{ ansible_facts.user_dir }}/.bashrc"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600

- name: Apply sysctl settings
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  loop:
    # IPv4 forwarding - needed for k3s
    - { name: 'net.ipv4.ip_forward', value: '1' }
    # Raise the maximum number of open files
    - { name: 'fs.inotify.max_queued_events', value: '32768' }
    - { name: 'fs.inotify.max_user_instances', value: '512' }
    - { name: 'fs.inotify.max_user_watches', value: '524288' }
    # Cause who needs IPv6
    - { name: 'net.ipv6.conf.all.disable_ipv6', value: '1' }
    - { name: 'net.ipv6.conf.default.disable_ipv6', value: '1' }
