---
- name: Allow SSH
  ufw:
    rule: allow
    proto: tcp
    port: "22"

- name: Enable UFW
  ufw:
    state: enabled
    policy: deny

- name: Allow localhost
  ufw:
    rule: allow
    interface: lo
    direction: in
