---
- name: Allow SSH
  ufw:
    rule: allow
    proto: tcp
    port: "22"
  register: ufw_result
  until: ufw_result is succeeded
  retries: 5
  delay: 2

- name: Enable UFW
  ufw:
    state: enabled
    policy: deny
  register: ufw_result
  until: ufw_result is succeeded
  retries: 5
  delay: 2

- name: Allow localhost
  ufw:
    rule: allow
    interface: lo
    direction: in
  register: ufw_result
  until: ufw_result is succeeded
  retries: 5
  delay: 2
