---
- import_tasks: packages.yaml
- import_tasks: config.yaml
- import_tasks: firewall.yaml

# TODO: Fix these
# - name: Set default DNS for all interfaces
#   lineinfile:
#     path: /etc/resolv.conf
#     line: 'nameserver 8.8.8.8' # You can replace 8.8.8.8 with your preferred DNS server

- name: Add IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^.* {{ inventory_hostname }} {{ inventory_hostname_short }}$'
    line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ inventory_hostname_short }}"
    state: present
  when: inventory_hostname != item
  with_items: "{{ groups.all }}"
