---

- name: Install required packages
  apt:
    autoclean: yes
    autoremove: yes
    state: latest
    update_cache: yes
    upgrade: dist
    name: hostapd
  notify:
    - restart hostapd

- name: Copy hostapd config
  template:
    src: templates/hostapd.conf
    dest: /etc/hostapd/hostapd.conf
    owner: root
    group: root
    mode: "0600"
