name = "Only Create"
author = "Dimitris Zervas"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd1fed1f9453ce262cbeb680f53614a20b821e03ed1529a0362729aa83ca8ad6"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"
