---
- name: Update ZeroTier configuration
  copy:
    src: local.conf
    dest: /var/lib/zerotier-one/local.conf
    owner: zerotier-one
    group: zerotier-one
    mode: '0644'
  notify: Restart ZeroTier service

- name: Update ZeroTier identity secret
  copy:
    content: "{{ hostvars[inventory_hostname].zerotier_identity.private }}"
    dest: /var/lib/zerotier-one/identity.secret
    owner: zerotier-one
    group: zerotier-one
    mode: '0600'
  when:
    - hostvars[inventory_hostname].zerotier_identity is defined
    - hostvars[inventory_hostname].zerotier_identity.private is defined
  notify: Restart ZeroTier service

- name: Update ZeroTier identity public
  copy:
    content: "{{ hostvars[inventory_hostname].zerotier_identity.public }}"
    dest: /var/lib/zerotier-one/identity.public
    owner: zerotier-one
    group: zerotier-one
    mode: '0644'
  when:
    - hostvars[inventory_hostname].zerotier_identity is defined
    - hostvars[inventory_hostname].zerotier_identity.public is defined
  notify: Restart ZeroTier service
