---
- name: Update ZeroTier configuration
  copy:
    src: local.conf
    dest: /var/lib/zerotier-one/local.conf
    owner: zerotier-one
    group: zerotier-one
    mode: '0644'
  notify: Restart ZeroTier service

- name: Update ZeroTier identity secret
  copy:
    content: "{{ hostvars[inventory_hostname].zerotier_identity.private }}"
    dest: /var/lib/zerotier-one/identity.secret
    owner: zerotier-one
    group: zerotier-one
    mode: '0600'
  when: '"zerotier_identity" in hostvars[inventory_hostname]'
  notify: Restart ZeroTier service

- name: Update ZeroTier identity public
  copy:
    content: "{{ hostvars[inventory_hostname].zerotier_identity.public }}"
    dest: /var/lib/zerotier-one/identity.public
    owner: zerotier-one
    group: zerotier-one
    mode: '0644'
  when: '"zerotier_identity" in hostvars[inventory_hostname]'
  notify: Restart ZeroTier service
