---
- name: Install DNSMasq
  apt:
    name: dnsmasq
    state: present

- name: Configure DNSMasq
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart DNSMasq

- name: Enable DNSMasq
  service:
    name: dnsmasq
    enabled: yes
    state: started
