---
- name: Allow ZeroTier traffic
  ufw:
    rule: allow
    proto: "{{ item }}"
    port: "9993"
  loop:
    - tcp
    - udp

- name: Open all ports on ZeroTier interface
  ufw:
    rule: allow
    interface: zt+
    direction: in
