---
- name: Allow ZeroTier traffic
  ufw:
    rule: allow
    proto: "{{ item }}"
    port: "9993"
  loop:
    - tcp
    - udp
  register: ufw_result
  until: ufw_result is succeeded
  retries: 5
  delay: 2

- name: Open all ports on ZeroTier interface
  ufw:
    rule: allow
    interface: zt+
    direction: in
  register: ufw_result
  until: ufw_result is succeeded
  retries: 5
  delay: 2
