---
- import_tasks: install.yaml
- import_tasks: config.yaml
- import_tasks: firewall.yaml
  tags: firewall

- name: Start ZeroTier service
  service:
    name: zerotier-one
    state: started
    enabled: true

# TODO: Populate the variable
# - name: Join ZeroTier network
#   command: zerotier-cli join {{ zerotier_network_id }}
#   args:
#     creates: /var/lib/zerotier-one/networks.d/{{ zerotier_network_id }}.conf

- meta: flush_handlers

- name: Wait for other hosts to be reachable
  wait_for:
    host: "{{ hostvars[item].zerotier_ip }}"
    port: 22
    delay: 1
    timeout: 60
  loop: "{{ groups.all | difference([inventory_hostname]) }}"

- import_tasks: dns.yaml
  when: inventory_hostname not in groups.agent
