---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: loki
  namespace: kube-system
  labels:
    logme: "true"
spec:
  chart: loki
  repo: https://grafana.github.io/helm-charts
  version: 5.14.1
  targetNamespace: grafana
  valuesContent: |-
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
    singleBinary:
      replicas: 1
      persistence:
        size: 20Gi
        storageClassName: longhorn

    gateway:
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
          nginx.ingress.kubernetes.io/auth-tls-secret: "cert-manager/client-ca-certificate"
          nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
        hosts:
          - host: logs.dzerv.art
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - logs.dzerv.art
            secretName: logs-dzerv-art-cert

    # Use our own
    monitoring:
      selfMonitoring:
        grafanaAgent:
          installOperator: false
