version: '3'

services:
  esphome:
    image: esphome/esphome:latest
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /data/esp/esphome:/config
    expose:
      - 6052
    environment:
      TZ: "${TZ}"
    labels:
      traefik.enable: true
      traefik.http.routers.esp.rule: "Host(`esp.${HOMELAB_DOMAIN}`)"
      traefik.http.routers.esp.entrypoints: websecure
      traefik.http.routers.esp.middlewares: authelia@docker

networks:
  proxy:
    external:
      name: proxy
