---

version: "3.2"

services:
  emby:
    image: linuxserver/emby
    restart: unless-stopped
    networks:
      - default
      - proxy
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "${TZ}"
      UMASK_SET: "022"
    volumes:
      - /data/watch/emby:/config
      - /data-tmp/watch/shows:/data/tvshows
      - /data-tmp/watch/movies:/data/movies
      - /data-tmp/watch/downloads:/data/downloads
      - /data-tmp/watch/transcode:/data/transcode
    expose:
      - 8096
    ports:
      - 8096:8096
    labels:
      traefik.enable: true
      traefik.http.routers.emby.rule: "Host(`watch.${HOMELAB_DOMAIN}`)"
      traefik.http.routers.emby.entrypoints: websecure

  ombi:
    image: linuxserver/ombi
    restart: unless-stopped
    networks:
      - default
      - proxy
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "${TZ}"
      BASE_URL: /ombi #optional
    volumes:
      - /data/watch/ombi:/config
    expose:
      - 3579
    labels:
      traefik.enable: true
      traefik.http.routers.ombi.rule: "Host(`watch.${HOMELAB_DOMAIN}`) && PathPrefix(`/ombi`)"
      traefik.http.routers.ombi.entrypoints: websecure

  jackett:
    image: linuxserver/jackett
    restart: unless-stopped
    networks:
      - default
      - proxy
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "${TZ}"
      # AUTO_UPDATE: "true"  # Ouroboros takes care of it
      # RUN_OPTS: run options here # optional
    volumes:
      - /data/watch/jackett:/config
      - /data-tmp/watch/downloads:/downloads
    expose:
      - 9117
    labels:
      traefik.enable: true
      traefik.http.routers.jackett.rule: "Host(`search.watch.${HOMELAB_DOMAIN}`)"
      traefik.http.routers.jackett.entrypoints: websecure
      traefik.http.routers.jackett.middlewares: authelia@docker

  qbittorrent:
    image: linuxserver/qbittorrent
    restart: unless-stopped
    networks:
      - default
      - proxy
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "${TZ}"
      UMASK_SET: "022"
      WEBUI_PORT: 8080
    volumes:
      - /data/watch/qbittorrent:/config
      - /data-tmp/watch/downloads:/downloads
    expose:
      - 8080
    # ports:
      # - 6881:6881
      # - 6881:6881/udp
      # - 8080:8080
    labels:
      traefik.enable: true
      traefik.http.routers.qbittorrent.rule: "Host(`torrents.watch.${HOMELAB_DOMAIN}`)"
      traefik.http.routers.qbittorrent.entrypoints: websecure
      traefik.http.routers.qbittorrent.middlewares: authelia@docker
      traefik.http.services.qbittorrent.loadbalancer.server.port: 8080

  sonarr:
    image: linuxserver/sonarr
    restart: unless-stopped
    networks:
      - default
      - proxy
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "${TZ}"
    expose:
      - 8989
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/watch/sonarr:/config
      - /data-tmp/watch/downloads:/downloads
      - /data-tmp/watch/shows:/shows
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.rule: "Host(`shows.watch.${HOMELAB_DOMAIN}`)"
      traefik.http.routers.sonarr.entrypoints: websecure
      traefik.http.routers.sonarr.middlewares: authelia@docker

  radarr:
    image: linuxserver/radarr
    restart: unless-stopped
    networks:
      - default
      - proxy
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "${TZ}"
    expose:
      - 7878
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/watch/radarr:/config
      - /data-tmp/watch/downloads:/downloads
      - /data-tmp/watch/movies:/movies
    labels:
      traefik.enable: true
      traefik.http.routers.radarr.rule: "Host(`movies.watch.${HOMELAB_DOMAIN}`)"
      traefik.http.routers.radarr.entrypoints: websecure
      traefik.http.routers.radarr.middlewares: authelia@docker

  bazarr:
    image: linuxserver/bazarr
    restart: unless-stopped
    networks:
      - default
      - proxy
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "${TZ}"
      UMASK_SET: "022"
    expose:
      - 6767
    volumes:
      - /data/watch/bazarr:/config
      - /data-tmp/watch/shows:/shows
      - /data-tmp/watch/movies:/movies
    labels:
      traefik.enable: true
      traefik.http.routers.bazarr.rule: "Host(`subs.watch.${HOMELAB_DOMAIN}`)"
      traefik.http.routers.bazarr.entrypoints: websecure
      traefik.http.routers.bazarr.middlewares: authelia@docker

networks:
  proxy:
    external:
      name: proxy
