---

- hosts: jira
  roles:
    - role: alvistack.jira
      vars:
        jira_version: "8.8.0"
        mysql_jdbc_version: "5.1.48"
        postgresql_jdbc_version: "42.2.12"
        jira_jvm_minimum_memory: "512m"
        jira_jvm_maximum_memory: "1024m"
        jira_session_timeout: "300"
