---

- hosts: server
  vars_files: ~/.homelab/server.yml
  become: yes
  become_method: sudo
  roles:
    - role: brianshumate.consul
      vars:
        consul_version: 1.7.2
        consul_config_path: /data/consul/config
        consul_data_path: /data/consul/data
        consul_datacenter: home
        consul_group_name: server
        consul_log_rotate_max_files: 7
        consul_domain: "{{ homelab_domain }}"
        consul_node_name: "{{ homelab_hostname }}"
        consul_install_upgrade: yes
        consul_bind_address: 127.0.0.1
        #consul_bind_address: 0.0.0.0
        consul_advertise_address: 127.0.0.1
        consul_advertise_address_wan: 10.13.37.80
        #consul_advertise_addresses_rpc: "{{ consul_advertise_address }}"
        consul_addresses_http: 0.0.0.0
        #consul_client_address: 127.0.0.1
        consul_recursors: "{{ homelab_dns }}"
        consul_raw_key: "{{ homelab_encrypt }}"
        consul_connect_enable: yes
        consul_node_role: bootstrap
        consul_acl_enable: yes
        consul_acl_default_policy: deny
        consul_acl_token_persistence: yes

    - role: brianshumate.vault
      vars:
        vault_version: 1.3.4
        vault_config_path: /data/vault/config
        vault_plugin_path: /data/vault/plugin
        vault_data_path: /data/vault/data
        vault_tls_config_path: /data/vault/tls
        vault_datacenter: home
        vault_cluster_disable: yes
        vault_address: 127.0.0.1
        vault_consul_token: "{{ homelab_consul_token }}"
        #vault_tls_disable: no

    - role: brianshumate.nomad
      vars:
        nomad_version: 0.10.5
        nomad_config_dir: /data/nomad/config
        nomad_data_dir: /data/nomad/data
        nomad_datacenter: home
        nomad_docker_enable: yes
        nomad_group_name: server
        nomad_iface: lo
        nomad_bind_address: 127.0.0.1
        nomad_advertise_address: 127.0.0.1
        nomad_use_consul: yes
        nomad_node_role: both
        nomad_bootstrap_expect: 1
        nomad_encrypt: "{{ homelab_encrypt }}"
        nomad_acl_enabled: yes
        nomad_vault_enabled: yes
        nomad_vault_address: http://127.0.0.1:8200
        nomad_vault_allow_unauthenticated: no
        nomad_consul_token: "{{ homelab_consul_token }}"
        nomad_vault_token: "{{ homelab_vault_token }}"
        nomad_host_volumes:
          - name: data
            path: /data/nomad/containers
            owner: "{{ nomad_user }}"
            group: "{{ nomad_group }}"
            mode: 0755
            read_only: false
