version: '3'

services:
  postgresql:
    image: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: airflow
      POSTGRES_DB: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_ENCODING: UNICODE
      POSTGRES_COLLATE: C
      POSTGRES_COLLATE_TYPE: C
    volumes:
      - /data/cron/postgresql:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - /data/cron/redis:/data
    environment:
      TZ: "${HOMELAB_TZ}"

  airflow-scheduler:
    image: bitnami/airflow-scheduler
    environment:
      AIRFLOW_DATABASE_NAME: airflow
      AIRFLOW_DATABASE_USERNAME: airflow
      AIRFLOW_DATABASE_PASSWORD: airflow
      AIRFLOW_EXECUTOR: CeleryExecutor
    volumes:
      - /data/cron/airflow/scheduler:/bitnami

  # Needs chown -R 1001 /data/cron/airflow/*
  airflow:
    image: bitnami/airflow
    networks:
      - default
      - proxy
    environment:
      AIRFLOW_DATABASE_NAME: airflow
      AIRFLOW_DATABASE_USERNAME: airflow
      AIRFLOW_DATABASE_PASSWORD: airflow
      AIRFLOW_EXECUTOR: CeleryExecutor
    volumes:
      - /data/cron/airflow/data:/bitnami
    labels:
      traefik.enable: true
      traefik.http.routers.cron.rule: "Host(`cron.${HOMELAB_DOMAIN}`)"
      traefik.http.routers.cron.entrypoints: websecure
      traefik.http.routers.cron.middlewares: authelia@docker

networks:
  proxy:
    external:
      name: proxy
