driver={{ hostapd_driver | default("nl80211") }}

logger_syslog=8
logger_syslog_level=3
logger_stdout=8
logger_stdout_level=3

ctrl_interface=/var/run/hostapd
ctrl_interface_group=sudo

# Operation mode (a = IEEE 802.11a (5 GHz), b = IEEE 802.11b (2.4 GHz),
# g = IEEE 802.11g (2.4 GHz), ad = IEEE 802.11ad (60 GHz); a/g options are used
# with IEEE 802.11n (HT), too, to specify band). For IEEE 802.11ac (VHT), this
# needs to be set to hw_mode=a.
hw_mode=g
channel=11
beacon_int=100
#country_code=US

ieee80211d={{ hostapd_80211d | default(0) }}
ieee80211h={{ hostapd_80211h | default(0) }}
ieee80211n={{ hostapd_80211n | default(1) }}
ieee80211w={{ hostapd_80211w | default(1) }}
ieee80211ac={{ hostapd_80211ac | default(0) }}
ieee80211ax={{ hostapd_80211ax | default(0) }}

# Only PSK
auth_algs=1
#require_vht=1
#vht_oper_chwidth=1
#vht_oper_centr_freq_seg0_idx=46

# Network configuration

{% for interface, network in hostapd_networks.items() %}
{% for ssid, config in network.items() %}

# {{ ssid }} -> {{ config.bridge }}
{% if loop.first %}
interface={{ interface }}
{% else %}
bss={{ interface }}_{{ count.index0 - 1 }}
{% endif %}
{% if config.bridge is not None %}
bridge={{ config.bridge }}
{% endif %}
ssid2="{{ ssid }}"
wpa=2
wpa_passphrase={{ config.passphrase }}
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
ignore_broadcast_ssid={{ config.hidden | default(0) }}
{% endor %}
{% endor %}
