version: '3'

services:
  jira:
    depends_on:
      - postgresql
    image: atlassian/jira-software
    restart: unless-stopped
    networks:
      - default
      - proxy
    volumes:
      - /data/jira/jira:/var/atlassian/application-data/jira
      - /data/certs/default.crt:/proxy.crt:ro
    environment:
      CATALINA_CONNECTOR_PROXYNAME: "jira.${DOMAIN}"
      CATALINA_CONNECTOR_PROXYPORT: 443
      CATALINA_CONNECTOR_SCHEME: https
      CATALINA_CONNECTOR_SECURE: "true"
      JVM_SUPPORT_RECOMMENDED_ARGS: -Djavax.net.ssl.trustStore=/var/atlassian/application-data/jira/cacerts
    labels:
      traefik.enable: true
      traefik.http.routers.jira.rule: "Host(`jira.${DOMAIN}`)"
      traefik.http.routers.jira.entrypoints: websecure

  postgresql:
    image: postgres:11-alpine
    restart: unless-stopped
    volumes:
      - /data/jira/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: jellyfish
      POSTGRES_DB: jiradb
      POSTGRES_ENCODING: UNICODE
      POSTGRES_COLLATE: C
      POSTGRES_COLLATE_TYPE: C

networks:
  proxy:
    external:
      name: proxy
