version: '3'

services:
  jira:
    depends_on:
      - postgres
    image: atlassian/jira-software
    restart: unless-stopped
    networks:
      - default
      - proxy
    volumes:
      - /data/jira/jira:/var/atlassian/application-data/jira
    environment:
      CATALINA_CONNECTOR_PROXYNAME: "jira.${HOMELAB_DOMAIN}"
      CATALINA_CONNECTOR_PROXYPORT: 443
      CATALINA_CONNECTOR_SCHEME: https
      CATALINA_CONNECTOR_SECURE: "true"
      JVM_MINIMUM_MEMORY: 512m
      JVM_MAXIMUM_MEMORY: 2048m
    labels:
      traefik.enable: true
      traefik.http.routers.jira.rule: "Host(`jira.${HOMELAB_DOMAIN}`)"
      traefik.http.routers.jira.entrypoints: websecure
      traefik.http.routers.jira.middlewares: authelia@docker

  postgres:
    image: postgres:11-alpine
    restart: unless-stopped
    volumes:
      - /data/jira/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: jira
      POSTGRES_DB: jiradb
      POSTGRES_ENCODING: UNICODE
      POSTGRES_COLLATE: C
      POSTGRES_COLLATE_TYPE: C

networks:
  proxy:
    external:
      name: proxy
