when:
  - event: push
    branch: main
    path:
      include:
        - .woodpecker/docker.yaml
        - docker/${image}/**
      on_empty: false

matrix:
  image:
    - dns-controller
    - netshoot
    - affine

steps:
  - name: publish-image
    image: plugins/kaniko
    settings:
      registry: git.vpn.dzerv.art
      repo: git.vpn.dzerv.art/${CI_REPO}/${image}
      username: ${CI_REPO_OWNER}
      password:
        from_secret: forgejo_token

      context: docker/${image}
      dockerfile: docker/${image}/Dockerfile
      platforms: linux/amd64,linux/arm64
      auto_tag: true # git tag or latest
