version: "3"

services:
  authelia:
    image: authelia/authelia
    restart: unless-stopped
    hostname: authelia
    volumes:
      - /data/auth/authelia:/var/lib/authelia
      - /data/auth/authelia.yml:/etc/authelia/configuration.yml:ro
      - /data/auth/users_database.yml:/etc/authelia/users_database.yml
    networks:
      - default
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.authelia.rule: "Host(`auth.${HOMELAB_DOMAIN}`)"
      traefik.http.routers.authelia.entrypoints: websecure
      traefik.http.middlewares.authelia.forwardauth.address: "http://authelia:9091/api/verify?rd=https://auth.${HOMELAB_DOMAIN}"
      traefik.http.middlewares.authelia.forwardauth.trustForwardHeader: true
    environment:
      TZ: "${HOMELAB_TZ}"

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - /data/auth/redis:/data
    environment:
      TZ: "${HOMELAB_TZ}"

networks:
  proxy:
    external:
      name: proxy
