---

- name: Install required packages
  apt:
    state: latest
    name:
      - dnsmasq-base
      - dnsmasq
  notify: restart dnsmasq

- name: Copy configuration
  template:
    src: templates/dnsmasq.conf
    dest: /etc/dnsmasq.conf
    state: present
    backup: yes
  notify: restart dnsmasq
