---

- name: Install hostapd required packages
  apt:
    state: latest
    name: hostapd
  notify: restart hostapd

- name: Copy hostapd configuration
  template:
    src: templates/hostapd.conf
    dest: /etc/hostapd/hostapd.conf
    backup: yes
  notify: restart hostapd
