---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
  namespace: cert-manager
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: client-ca
  namespace: cert-manager
spec:
  secretName: client-ca-certificate
  dnsNames:
    - k8s.dzervas.gr
    - "*.k8s.dzervas.gr"
    - staging.blogaki.io
    - staging.dzerv.it
  subject:
    organizations:
      - k8s.dzervas.gr
  duration: 87658h # 10 years
  privateKey:
    algorithm: ECDSA
    size: 384
  isCA: true

  issuerRef:
    name: selfsigned
    kind: ClusterIssuer

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: client-ca
  namespace: cert-manager
spec:
  ca:
    secretName: client-ca-certificate
