---
- import_tasks: ../system/handlers/main.yaml

- name: Restart multipathd service
  service:
    name: multipathd
    state: restarted

- name: Restart k3s service
  service:
    name: k3s
    state: restarted
    enabled: yes
    daemon_reload: yes
