---
- name: Restart multipathd service
  service:
    name: multipathd
    state: restarted

- name: Restart k3s service
  service:
    name: k3s
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Restart WireGuard service
  service:
    name: wg-quick@wg0.service
    state: restarted
    enabled: yes
    daemon_reload: yes
