---
- name: Restart journald service
  service:
    name: systemd-journald
    state: restarted

- name: save iptables
  community.general.iptables_state:
    state: saved
    path: /etc/iptables/rules
